"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Loader2, Copy, Check, Sparkles, Film, ExternalLink, AlertCircle } from "lucide-react";
import { SubtitleSearch, type MediaResult } from "./subtitle-search";

const VPS_API_BASE =
  process.env.NEXT_PUBLIC_API_URL || "https://api.cinestream.biz.id";

export function SubtitleGenerate() {
  const [apiKey, setApiKey] = useState("");
  const [selectedMedia, setSelectedMedia] = useState<MediaResult | null>(null);
  const [season, setSeason] = useState("1");
  const [episode, setEpisode] = useState("1");
  const [command, setCommand] = useState("");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("admin_api_key");
    if (saved) setApiKey(saved);
  }, []);

  useEffect(() => {
    if (apiKey) localStorage.setItem("admin_api_key", apiKey);
  }, [apiKey]);

  useEffect(() => {
    if (selectedMedia?.type === "movie") {
      setSeason("");
      setEpisode("");
    } else if (selectedMedia?.type === "tv" && !season) {
      setSeason("1");
      setEpisode("1");
    }
  }, [selectedMedia]);

  const handleGenerate = () => {
    if (!selectedMedia || !apiKey) return;

    const isTV = selectedMedia.type === "tv";
    const title = selectedMedia.title;
    const cinemacityId = selectedMedia.cinemacity_id;
    const slug = selectedMedia.slug;
    const type = selectedMedia.type;

    const streamParams = new URLSearchParams({
      slug: slug,
      type: type,
    });
    if (isTV && season) streamParams.set("season", season);
    if (isTV && episode) streamParams.set("episode", episode);
    const streamUrl = `${VPS_API_BASE}/api/stream/play/${cinemacityId}?${streamParams.toString()}`;

    const lines = [
      "# ============================================================",
      "# CINESTREAM SUBTITLE GENERATOR",
      "# Auto-generated by cinestream.biz.id/admin/subtitle/generate",
      "# ============================================================",
      `# Film: ${title}`,
      `# Type: ${type}`,
      `# Cinemacity ID: ${cinemacityId}`,
      isTV ? `# Season: ${season}, Episode: ${episode}` : "# Season/Episode: N/A (movie)",
      "# Model: Whisper small (Indonesia)",
      "# ============================================================",
      "",
      "# === CONFIGURATION ===",
      `STREAM_URL = "${streamUrl}"`,
      `TITLE = ${JSON.stringify(title)}`,
      `TYPE = "${type}"`,
      `SEASON = ${isTV && season ? JSON.stringify(season) : "None"}`,
      `EPISODE = ${isTV && episode ? JSON.stringify(episode) : "None"}`,
      `ADMIN_API_KEY = "${apiKey}"`,
      `WORKER_URL = "https://cinestream.biz.id"`,
      `WATERMARK = "nonton streaming film terupdate hanya di cinestream.biz.id"`,
      "",
      "# === STEP 1: Install Whisper ===",
      "import subprocess",
      "import sys",
      "print('Installing openai-whisper...')",
      "subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', 'openai-whisper'])",
      "print('Whisper installed')",
      "",
      "# === STEP 2: Download audio via Python requests (bukan ffmpeg langsung) ===",
      "# ffmpeg HTTP handling bermasalah dengan Cloudflare proxy.",
      "# Pakai Python requests untuk download HLS segments, lalu ffmpeg extract audio lokal.",
      "import requests",
      "import os",
      "import re",
      "",
      "HEADERS = {",
      "    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',",
      "    'Origin': 'https://cinestream.biz.id',",
      "    'Referer': 'https://cinestream.biz.id/',",
      "}",
      "",
      "BASE = 'https://api.cinestream.biz.id'",
      "",
      "print('Fetching m3u8 playlist...')",
      "resp = requests.get(STREAM_URL, headers=HEADERS, timeout=30)",
      "print(f'Status: {resp.status_code}')",
      "if resp.status_code != 200:",
      "    raise Exception(f'Failed to fetch m3u8: HTTP {resp.status_code}')",
      "m3u8_text = resp.text",
      "",
      "# Cari sub-playlist URL (kalau ada EXT-X-STREAM-INF)",
      "sub_url = None",
      "for line in m3u8_text.split(chr(10)):",
      "    line = line.strip()",
      "    if line and not line.startswith('#'):",
      "        sub_url = line",
      "        break",
      "",
      "if sub_url:",
      "    if sub_url.startswith('http'):",
      "        sub_full = sub_url",
      "    else:",
      "        sub_full = BASE + sub_url",
      "    print(f'Fetching sub-playlist: {sub_full[:80]}...')",
      "    resp2 = requests.get(sub_full, headers=HEADERS, timeout=30)",
      "    m3u8_text = resp2.text",
      "",
      "# Parse segment URLs",
      "segments = []",
      "for line in m3u8_text.split(chr(10)):",
      "    line = line.strip()",
      "    if line and not line.startswith('#'):",
      "        if line.startswith('http'):",
      "            segments.append(line)",
      "        else:",
      "            segments.append(BASE + line)",
      "",
      "total = len(segments)",
      "print(f'Found {total} segments')",
      "if total == 0:",
      "    raise Exception('No segments found in m3u8')",
      "",
      "# Download semua segments dan gabung jadi 1 file TS",
      "print(f'Downloading {total} segments...')",
      "with open('video.ts', 'wb') as f:",
      "    for i, seg_url in enumerate(segments):",
      "        seg_resp = requests.get(seg_url, headers=HEADERS, timeout=60)",
      "        if seg_resp.status_code == 200:",
      "            f.write(seg_resp.content)",
      "        else:",
      "            print(f'  WARNING: segment {i+1} failed (HTTP {seg_resp.status_code})')",
      "        if (i + 1) % 50 == 0:",
      "            pct = int((i + 1) / total * 100)",
      "            print(f'  Progress: {i+1}/{total} ({pct}%)')",
      "print(f'Downloaded {total} segments')",
      "",
      "# Extract audio dengan ffmpeg dari file lokal (tidak ada HTTP request)",
      "print('Extracting audio from video.ts...')",
      "subprocess.run([",
      "    'ffmpeg', '-y',",
      "    '-i', 'video.ts',",
      "    '-vn',",
      "    '-acodec', 'pcm_s16le',",
      "    '-ar', '16000',",
      "    '-ac', '1',",
      "    'audio.wav'",
      "], check=True, capture_output=True)",
      "print('Audio extracted: audio.wav')",
      "",
      "# Cleanup video.ts (hemat storage Colab)",
      "os.remove('video.ts')",
      "print('Cleaned up video.ts')",
      "",
      "# === STEP 3: Run Whisper transcription ===",
      "import whisper",
      "print('Loading Whisper model (small)...')",
      "print('First run akan download model (~500MB), tunggu sebentar...')",
      "model = whisper.load_model('small')",
      "print('Model loaded')",
      "print('Transcribing audio (language=id)...')",
      "result = model.transcribe('audio.wav', language='id', task='transcribe', verbose=True)",
      "print(f'Transcribed {len(result[segments])} segments')",
      "",
      "# === STEP 4: Convert to VTT + add watermark ===",
      "def seconds_to_vtt(sec):",
      "    h = int(sec // 3600)",
      "    m = int((sec % 3600) // 60)",
      "    s = int(sec % 60)",
      "    ms = int((sec % 1) * 1000)",
      "    return f'{h:02d}:{m:02d}:{s:02d}.{ms:03d}'",
      "",
      "NL = chr(10)",
      "vtt_lines = ['WEBVTT', '', 'NOTE', f'Subtitle generated by CineStream - {WORKER_URL}', '']",
      "vtt_lines.append('00:00:00.000 --> 00:00:01.500')",
      "vtt_lines.append(WATERMARK)",
      "vtt_lines.append('')",
      "segments_list = result['segments']",
      "next_wm = 300",
      "for seg in segments_list:",
      "    start = seg['start']",
      "    end = seg['end']",
      "    text = seg['text'].strip()",
      "    while start >= next_wm + 0.6:",
      "        wm_start = next_wm",
      "        wm_end = next_wm + 0.5",
      "        if wm_end <= start:",
      "            vtt_lines.append(f'{seconds_to_vtt(wm_start)} --> {seconds_to_vtt(wm_end)}')",
      "            vtt_lines.append(WATERMARK)",
      "            vtt_lines.append('')",
      "        next_wm += 300",
      "    vtt_lines.append(f'{seconds_to_vtt(start)} --> {seconds_to_vtt(end)}')",
      "    vtt_lines.append(text)",
      "    vtt_lines.append('')",
      "vtt_content = NL.join(vtt_lines)",
      "print(f'VTT generated ({len(vtt_content)} chars, {len(segments_list)} cues)')",
      "with open('subtitle.vtt', 'w', encoding='utf-8') as f:",
      "    f.write(vtt_content)",
      "print('Saved to subtitle.vtt (backup)')",
      "",
      "# === STEP 5: Upload ke CineStream API ===",
      "print('Uploading subtitle to CineStream...')",
      "resp = requests.post(",
      "    f'{WORKER_URL}/api/admin/subtitle',",
      "    headers={",
      "        'Content-Type': 'application/json',",
      "        'X-Admin-API-Key': ADMIN_API_KEY,",
      "    },",
      "    json={",
      "        'title': TITLE,",
      "        'type': TYPE,",
      "        'season': SEASON,",
      "        'episode': EPISODE,",
      "        'subtitle_text': vtt_content,",
      "        'release_name': 'whisper-small-auto-id',",
      "        'offset_seconds': 0,",
      "    },",
      "    timeout=30,",
      ")",
      "print('=' * 50)",
      "print(f'Upload status: {resp.status_code}')",
      "print(f'Response: {resp.json()}')",
      "if resp.status_code == 200:",
      "    print('SUCCESS! Subtitle tersimpan di CineStream.')",
      "    print(f'Buka {WORKER_URL}, cari film {TITLE}, play, subtitle muncul otomatis.')",
      "else:",
      "    print('FAILED. Cek error di atas.')",
      "print('=' * 50)",
    ];

    const colabScript = lines.join("\n");
    setCommand(colabScript);
    setCopied(false);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(command);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = command;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  const isTV = selectedMedia?.type === "tv";

  return (
    <div className="space-y-6">
      {!apiKey && (
        <div className="rounded-lg border border-yellow-500/30 bg-yellow-500/5 p-4">
          <Label className="text-sm font-semibold">Admin API Key</Label>
          <Input
            type="password"
            placeholder="Paste your ADMIN_API_KEY"
            value={apiKey}
            onChange={(e) => setApiKey(e.target.value)}
            className="mt-1"
          />
        </div>
      )}

      {apiKey && (
        <>
          <SubtitleSearch onSelect={setSelectedMedia} />

          {selectedMedia && isTV && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <h2 className="text-lg font-semibold">2. Pilih Episode</h2>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label htmlFor="season">Season</Label>
                  <Input id="season" type="number" value={season} onChange={(e) => setSeason(e.target.value)} placeholder="1" />
                </div>
                <div>
                  <Label htmlFor="episode">Episode</Label>
                  <Input id="episode" type="number" value={episode} onChange={(e) => setEpisode(e.target.value)} placeholder="1" />
                </div>
              </div>
            </div>
          )}

          {selectedMedia && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <h2 className="flex items-center gap-2 text-lg font-semibold">
                <Sparkles className="h-5 w-5 text-primary" />
                {isTV ? "3. Generate Colab Command" : "2. Generate Colab Command"}
              </h2>
              <div className="rounded-md bg-muted/50 p-3 text-sm">
                <div className="flex items-center gap-2">
                  <Film className="h-4 w-4 text-muted-foreground" />
                  <span className="font-medium">{selectedMedia.title}</span>
                </div>
                <div className="mt-2 flex flex-wrap gap-1">
                  <Badge variant="secondary" className="text-[10px]">{selectedMedia.type === "tv" ? "TV Series" : "Movie"}</Badge>
                  {isTV && season && <Badge variant="outline" className="text-[10px]">S{season}</Badge>}
                  {isTV && episode && <Badge variant="outline" className="text-[10px]">E{episode}</Badge>}
                  <Badge variant="outline" className="text-[10px]">ID: {selectedMedia.cinemacity_id}</Badge>
                </div>
              </div>
              <Button onClick={handleGenerate} className="w-full" size="lg">
                <Sparkles className="mr-2 h-4 w-4" />
                Generate Colab Command
              </Button>
            </div>
          )}

          {command && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <div className="flex items-center justify-between">
                <h2 className="flex items-center gap-2 text-lg font-semibold">
                  <Check className="h-5 w-5 text-green-500" />
                  {isTV ? "4. Copy & Paste ke Colab" : "3. Copy & Paste ke Colab"}
                </h2>
                <Button onClick={handleCopy} size="sm" variant={copied ? "default" : "outline"}>
                  {copied ? (<><Check className="mr-1 h-3 w-3" />Copied!</>) : (<><Copy className="mr-1 h-3 w-3" />Copy</>)}
                </Button>
              </div>
              <div className="rounded-md border border-blue-500/30 bg-blue-500/5 p-3 text-sm space-y-2">
                <p className="font-semibold">Cara pakai:</p>
                <ol className="list-decimal list-inside space-y-1 text-xs text-muted-foreground">
                  <li>Buka <a href="https://colab.research.google.com" target="_blank" rel="noopener noreferrer" className="text-blue-500 underline inline-flex items-center gap-0.5">Google Colab <ExternalLink className="h-3 w-3" /></a></li>
                  <li>Buat notebook baru (New Notebook)</li>
                  <li>Paste command ke cell pertama</li>
                  <li>Runtime → Change runtime type → T4 GPU</li>
                  <li>Klik Run (Shift+Enter)</li>
                  <li>Tunggu ~10-20 menit (download segments + transcribe)</li>
                  <li>Subtitle otomatis ter-upload ke CineStream</li>
                </ol>
              </div>
              <div className="rounded-md border border-orange-500/30 bg-orange-500/5 p-3 text-xs text-orange-600">
                <p className="flex items-start gap-2">
                  <AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />
                  <span><strong>Penting:</strong> Pakai GPU runtime (T4) untuk kecepatan optimal. Download segments ~5-10 menit, transcribe ~5-10 menit.</span>
                </p>
              </div>
              <div>
                <Label>Python Command (copy semua)</Label>
                <textarea readOnly value={command} className="mt-1 min-h-[400px] w-full rounded-md border border-input bg-zinc-950 px-3 py-2 font-mono text-xs text-green-400" onClick={(e) => (e.target as HTMLTextAreaElement).select()} />
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
