"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Loader2, Copy, Check, Sparkles, Film, ExternalLink, AlertCircle } from "lucide-react";
import { SubtitleSearch, type MediaResult } from "./subtitle-search";

const VPS_API_BASE =
  process.env.NEXT_PUBLIC_API_URL || "/api/vps";

const MODELS = [
  { id: "small", label: "Small (Cepat, ~500MB, Akurat cukup)", size: "500MB", speed: "5-10 mnt" },
  { id: "medium", label: "Medium (Seimbang, ~1.5GB, Akurat baik)", size: "1.5GB", speed: "15-30 mnt" },
  { id: "large-v3", label: "Large v3 (Lambat, ~3GB, Paling akurat)", size: "3GB", speed: "30-60 mnt" },
];

export function SubtitleGenerate() {
  const [apiKey, setApiKey] = useState("");
  const [selectedMedia, setSelectedMedia] = useState<MediaResult | null>(null);
  const [season, setSeason] = useState("1");
  const [episode, setEpisode] = useState("1");
  const [model, setModel] = useState("large-v3");
  const [audioLang, setAudioLang] = useState("auto");  // FIX: auto-detect bahasa audio
  const [translateToId, setTranslateToId] = useState(true);  // FIX: translate ke Indonesia kalau bukan Indonesia
  const [command, setCommand] = useState("");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("admin_api_key");
    if (saved) setApiKey(saved);
  }, []);

  useEffect(() => {
    if (apiKey) localStorage.setItem("admin_api_key", apiKey);
  }, [apiKey]);

  useEffect(() => {
    if (selectedMedia?.type === "movie") {
      setSeason("");
      setEpisode("");
    } else if (selectedMedia?.type === "tv" && !season) {
      setSeason("1");
      setEpisode("1");
    }
  }, [selectedMedia]);

  const handleGenerate = () => {
    if (!selectedMedia || !apiKey) return;

    const isTV = selectedMedia.type === "tv";
    const title = selectedMedia.title;
    const cinemacityId = selectedMedia.cinemacity_id;
    const slug = selectedMedia.slug;
    const type = selectedMedia.type;

    const streamParams = new URLSearchParams({
      slug: slug,
      type: type,
    });
    if (isTV && season) streamParams.set("season", season);
    if (isTV && episode) streamParams.set("episode", episode);
    const streamUrl = `${VPS_API_BASE}/api/stream/play/${cinemacityId}?${streamParams.toString()}`;

    const lines = [
      "# ============================================================",
      "# CINESTREAM SUBTITLE GENERATOR v4",
      "# Auto-generated by cinestream.biz.id/admin/subtitle/generate",
      "# ============================================================",
      `# Film: ${title}`,
      `# Type: ${type}`,
      `# Cinemacity ID: ${cinemacityId}`,
      isTV ? `# Season: ${season}, Episode: ${episode}` : "# Season/Episode: N/A (movie)",
      `# Model: Whisper ${model} (Indonesia)`,
      "# ============================================================",
      "",
      "# === CONFIGURATION ===",
      `STREAM_URL = "${streamUrl}"`,
      `TITLE = ${JSON.stringify(title)}`,
      `TYPE = "${type}"`,
      `SEASON = ${isTV && season ? JSON.stringify(season) : "None"}`,
      `EPISODE = ${isTV && episode ? JSON.stringify(episode) : "None"}`,
      `ADMIN_API_KEY = "${apiKey}"`,
      `WORKER_URL = "https://cinestream.biz.id"`,
      `WATERMARK = "nonton streaming film terupdate hanya di cinestream.biz.id"`,
      `MODEL_NAME = "${model}"`,
      `AUDIO_LANG = ${audioLang === "auto" ? "None" : "'" + audioLang + "'"}  # None = auto-detect, or 'en', 'id'`,
      `TRANSLATE_TO_ID = ${translateToId ? "True" : "False"}  # True = translate ke Indonesia kalau bahasa asli bukan id`,
      "",
      "# === STEP 1: Install Whisper ===",
      "import subprocess",
      "import sys",
      "import time",
      "print('Installing openai-whisper...')",
      "subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', 'openai-whisper'])",
      "print('Whisper installed')",
      "",
      "# === STEP 2: Download audio via Python requests ===",
      "# Pakai delay + retry untuk avoid Cloudflare rate limit (429)",
      "import requests",
      "import os",
      "",
      "HEADERS = {",
      "    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',",
      "    'Origin': 'https://cinestream.biz.id',",
      "    'Referer': 'https://cinestream.biz.id/',",
      "}",
      "",
      "BASE = 'https://api.cinestream.biz.id'",
      "",
      "def fetch_with_retry(url, max_retries=3):",
      "    for attempt in range(max_retries):",
      "        try:",
      "            resp = requests.get(url, headers=HEADERS, timeout=60)",
      "            if resp.status_code == 200:",
      "                return resp",
      "            elif resp.status_code == 429:",
      "                wait = 5 * (attempt + 1)",
      "                print(f'    Rate limited, waiting {wait}s...')",
      "                time.sleep(wait)",
      "            else:",
      "                print(f'    HTTP {resp.status_code}, retry...')",
      "                time.sleep(2)",
      "        except Exception as e:",
      "            print(f'    Error: {e}, retry...')",
      "            time.sleep(2)",
      "    return None",
      "",
      "print('Fetching m3u8 playlist...')",
      "resp = fetch_with_retry(STREAM_URL)",
      "if not resp:",
      "    raise Exception('Failed to fetch m3u8 after retries')",
      "print(f'Status: {resp.status_code}')",
      "m3u8_text = resp.text",
      "",
      "sub_url = None",
      "for line in m3u8_text.split(chr(10)):",
      "    line = line.strip()",
      "    if line and not line.startswith('#'):",
      "        sub_url = line",
      "        break",
      "",
      "if sub_url:",
      "    if sub_url.startswith('http'):",
      "        sub_full = sub_url",
      "    else:",
      "        sub_full = BASE + sub_url",
      "    print(f'Fetching sub-playlist...')",
      "    resp2 = fetch_with_retry(sub_full)",
      "    if resp2:",
      "        m3u8_text = resp2.text",
      "",
      "segments = []",
      "import base64",
      "for line in m3u8_text.split(chr(10)):",
      "    line = line.strip()",
      "    if line and not line.startswith('#'):",
      "        if 'easyproxy' in line:",
      "            path = line.replace('http://easyproxy:7860', '')",
      "            b64 = base64.urlsafe_b64encode(path.encode()).decode().rstrip('=')",
      "            segments.append(BASE + '/api/stream/segment?p=' + b64)",
      "        elif line.startswith('http'):",
      "            segments.append(line)",
      "        else:",
      "            segments.append(BASE + line)",
      "",
      "total = len(segments)",
      "print(f'Found {total} segments')",
      "if total == 0:",
      "    raise Exception('No segments found')",
      "",
      "print(f'Downloading {total} segments (with retry + delay)...')",
      "failed = 0",
      "with open('video.ts', 'wb') as f:",
      "    for i, seg_url in enumerate(segments):",
      "        seg_resp = fetch_with_retry(seg_url)",
      "        if seg_resp:",
      "            f.write(seg_resp.content)",
      "        else:",
      "            print(f'  FAILED: segment {i+1} (skipped)')",
      "            failed += 1",
      "        if (i + 1) % 50 == 0:",
      "            pct = int((i + 1) / total * 100)",
      "            print(f'  Progress: {i+1}/{total} ({pct}%)')",
      "        time.sleep(0.1)  # 100ms delay antar segment",
      "print(f'Downloaded {total - failed}/{total} segments ({failed} failed)')",
      "",
      "print('Extracting audio from video.ts...')",
      "subprocess.run([",
      "    'ffmpeg', '-y',",
      "    '-i', 'video.ts',",
      "    '-vn',",
      "    '-acodec', 'pcm_s16le',",
      "    '-ar', '16000',",
      "    '-ac', '1',",
      "    'audio.wav'",
      "], check=True, capture_output=True)",
      "print('Audio extracted: audio.wav')",
      "os.remove('video.ts')",
      "print('Cleaned up video.ts')",
      "",
      "# === STEP 3: Run Whisper transcription ===",
      "import whisper",
      "print(f'Loading Whisper model ({MODEL_NAME})...')",
      "print('First run akan download model, tunggu sebentar...')",
      "model = whisper.load_model(MODEL_NAME)",
      "print('Model loaded')",
      "print(f'Transcribing audio (language={AUDIO_LANG}, optimized for accuracy)...')",
      "# FIX: Tidak pakai initial_prompt (terlalu dominan, bikin Whisper generate teks random)",
      "# FIX: Tidak pakai condition_on_previous_text (bisa cascade error kalau 1 segment salah)",
      "result = model.transcribe(",
      "    'audio.wav',",
      "    language=AUDIO_LANG,   # None = auto-detect, or 'en', 'id'",
      "    task='transcribe',",
      "    verbose=False,",
      "    beam_size=10,",
      "    condition_on_previous_text=False,   # avoid cascade error",
      "    temperature=[0.0, 0.2, 0.4, 0.6],",
      "    compression_ratio_threshold=2.4,",
      "    no_speech_threshold=0.6,",
      ")",
      "segments_list = result['segments']",
      `detected_lang = result.get('language', 'unknown')`,
      `print(f'Transcribed {len(segments_list)} segments (detected language: {detected_lang})')`,
      "",
      "# === STEP 3b: Translate ke Indonesia kalau perlu ===",
      `if TRANSLATE_TO_ID and detected_lang != 'id':`,
      "    print(f'Translating from {detected_lang} to Indonesian...')",
      "    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', 'deep-translator'])",
      "    from deep_translator import GoogleTranslator",
      "    translator = GoogleTranslator(source='auto', target='id')",
      "    for seg in segments_list:",
      "        original = seg['text'].strip()",
      "        if original:",
      "            try:",
      "                translated = translator.translate(original)",
      "                seg['text'] = translated",
      "            except Exception as e:",
      "                print(f'  Translate failed for: {original[:30]}... ({e})')",
      "        if (segments_list.index(seg) + 1) % 50 == 0:",
      "            pct = int((segments_list.index(seg) + 1) / len(segments_list) * 100)",
      "            print(f'  Translate progress: {pct}%')",
      "    print('Translation complete')",
      "",
      "# === STEP 4: Convert to VTT + add watermark ===",
      "def seconds_to_vtt(sec):",
      "    h = int(sec // 3600)",
      "    m = int((sec % 3600) // 60)",
      "    s = int(sec % 60)",
      "    ms = int((sec % 1) * 1000)",
      "    return f'{h:02d}:{m:02d}:{s:02d}.{ms:03d}'",
      "",
      "NL = chr(10)",
      "vtt_lines = ['WEBVTT', '', 'NOTE', f'Subtitle generated by CineStream - {WORKER_URL}', '']",
      "vtt_lines.append('00:00:00.000 --> 00:00:01.500')",
      "vtt_lines.append(WATERMARK)",
      "vtt_lines.append('')",
      "next_wm = 300",
      "for seg in segments_list:",
      "    start = seg['start']",
      "    end = seg['end']",
      "    text = seg['text'].strip()",
      "    while start >= next_wm + 0.6:",
      "        wm_start = next_wm",
      "        wm_end = next_wm + 0.5",
      "        if wm_end <= start:",
      "            vtt_lines.append(f'{seconds_to_vtt(wm_start)} --> {seconds_to_vtt(wm_end)}')",
      "            vtt_lines.append(WATERMARK)",
      "            vtt_lines.append('')",
      "        next_wm += 300",
      "    vtt_lines.append(f'{seconds_to_vtt(start)} --> {seconds_to_vtt(end)}')",
      "    vtt_lines.append(text)",
      "    vtt_lines.append('')",
      "vtt_content = NL.join(vtt_lines)",
      "print(f'VTT generated ({len(vtt_content)} chars, {len(segments_list)} cues)')",
      "with open('subtitle.vtt', 'w', encoding='utf-8') as f:",
      "    f.write(vtt_content)",
      "print('Saved to subtitle.vtt (backup)')",
      "",
      "# === STEP 5: Upload ke CineStream API ===",
      "print('Uploading subtitle to CineStream...')",
      "resp = requests.post(",
      "    f'{WORKER_URL}/api/admin/subtitle',",
      "    headers={",
      "        'Content-Type': 'application/json',",
      "        'X-Admin-API-Key': ADMIN_API_KEY,",
      "    },",
      "    json={",
      "        'title': TITLE,",
      "        'type': TYPE,",
      "        'season': SEASON,",
      "        'episode': EPISODE,",
      "        'subtitle_text': vtt_content,",
      "        'release_name': f'whisper-{MODEL_NAME}-auto-id',",
      "        'offset_seconds': 0,",
      "    },",
      "    timeout=30,",
      ")",
      "print('=' * 50)",
      "print(f'Upload status: {resp.status_code}')",
      "print(f'Response: {resp.json()}')",
      "if resp.status_code == 200:",
      "    print('SUCCESS! Subtitle tersimpan di CineStream.')",
      "    print(f'Buka {WORKER_URL}, cari film {TITLE}, play, subtitle muncul otomatis.')",
      "else:",
      "    print('FAILED. Cek error di atas.')",
      "print('=' * 50)",
    ];

    const colabScript = lines.join("\n");
    setCommand(colabScript);
    setCopied(false);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(command);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = command;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  const isTV = selectedMedia?.type === "tv";

  return (
    <div className="space-y-6">
      {!apiKey && (
        <div className="rounded-lg border border-yellow-500/30 bg-yellow-500/5 p-4">
          <Label className="text-sm font-semibold">Admin API Key</Label>
          <Input
            type="password"
            placeholder="Paste your ADMIN_API_KEY"
            value={apiKey}
            onChange={(e) => setApiKey(e.target.value)}
            className="mt-1"
          />
        </div>
      )}

      {apiKey && (
        <>
          <SubtitleSearch onSelect={setSelectedMedia} />

          {selectedMedia && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <h2 className="text-lg font-semibold">2. Pilih Model AI</h2>
              <p className="text-xs text-muted-foreground">
                Model lebih besar = lebih akurat, tapi lebih lambat. Untuk bahasa Indonesia, "Medium" disarankan.
              </p>
              <div className="grid gap-2">
                {MODELS.map((m) => (
                  <button
                    key={m.id}
                    onClick={() => setModel(m.id)}
                    className={`flex items-center justify-between rounded-md border p-3 text-left transition ${
                      model === m.id
                        ? "border-primary bg-primary/5"
                        : "border-input hover:bg-muted/50"
                    }`}
                  >
                    <div>
                      <p className="text-sm font-medium">{m.label}</p>
                      <p className="text-[10px] text-muted-foreground">
                        Size: {m.size} · Estimasi: {m.speed}
                      </p>
                    </div>
                    {model === m.id && <Check className="h-4 w-4 text-primary" />}
                  </button>
                ))}
              </div>
            </div>
          )}

          {selectedMedia && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <h2 className="text-lg font-semibold">3. Bahasa Audio & Translate</h2>
              <div className="space-y-3">
                <div>
                  <Label>Bahasa Audio Film</Label>
                  <p className="text-xs text-muted-foreground mb-2">
                    Pilih bahasa asli audio film. "Auto-detect" = Whisper deteksi sendiri (paling akurat).
                  </p>
                  <div className="grid grid-cols-3 gap-2">
                    {[
                      { id: "auto", label: "Auto-detect" },
                      { id: "en", label: "English" },
                      { id: "id", label: "Indonesia" },
                    ].map((lang) => (
                      <button
                        key={lang.id}
                        onClick={() => setAudioLang(lang.id)}
                        className={`rounded-md border p-2 text-xs font-medium transition ${
                          audioLang === lang.id
                            ? "border-primary bg-primary/5"
                            : "border-input hover:bg-muted/50"
                        }`}
                      >
                        {lang.label}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="flex items-center gap-2 rounded-md bg-muted/50 p-3">
                  <button
                    onClick={() => setTranslateToId(!translateToId)}
                    className={`flex h-5 w-9 items-center rounded-full transition ${
                      translateToId ? "bg-primary" : "bg-muted"
                    }`}
                  >
                    <div className={`h-4 w-4 rounded-full bg-white transition ${translateToId ? "ml-4" : "ml-0.5"}`} />
                  </button>
                  <div>
                    <p className="text-sm font-medium">Translate ke Indonesia</p>
                    <p className="text-[10px] text-muted-foreground">
                      Kalau film bahasa Inggris/asing, otomatis translate ke Indonesia via Google Translate
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {selectedMedia && isTV && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <h2 className="text-lg font-semibold">4. Pilih Episode</h2>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label htmlFor="season">Season</Label>
                  <Input id="season" type="number" value={season} onChange={(e) => setSeason(e.target.value)} placeholder="1" />
                </div>
                <div>
                  <Label htmlFor="episode">Episode</Label>
                  <Input id="episode" type="number" value={episode} onChange={(e) => setEpisode(e.target.value)} placeholder="1" />
                </div>
              </div>
            </div>
          )}

          {selectedMedia && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <h2 className="flex items-center gap-2 text-lg font-semibold">
                <Sparkles className="h-5 w-5 text-primary" />
                {isTV ? "5. Generate Colab Command" : "4. Generate Colab Command"}
              </h2>
              <div className="rounded-md bg-muted/50 p-3 text-sm">
                <div className="flex items-center gap-2">
                  <Film className="h-4 w-4 text-muted-foreground" />
                  <span className="font-medium">{selectedMedia.title}</span>
                </div>
                <div className="mt-2 flex flex-wrap gap-1">
                  <Badge variant="secondary" className="text-[10px]">{selectedMedia.type === "tv" ? "TV Series" : "Movie"}</Badge>
                  {isTV && season && <Badge variant="outline" className="text-[10px]">S{season}</Badge>}
                  {isTV && episode && <Badge variant="outline" className="text-[10px]">E{episode}</Badge>}
                  <Badge variant="outline" className="text-[10px]">Model: {model}</Badge>
                </div>
              </div>
              <Button onClick={handleGenerate} className="w-full" size="lg">
                <Sparkles className="mr-2 h-4 w-4" />
                Generate Colab Command
              </Button>
            </div>
          )}

          {command && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <div className="flex items-center justify-between">
                <h2 className="flex items-center gap-2 text-lg font-semibold">
                  <Check className="h-5 w-5 text-green-500" />
                  {isTV ? "6. Copy & Paste ke Colab" : "5. Copy & Paste ke Colab"}
                </h2>
                <Button onClick={handleCopy} size="sm" variant={copied ? "default" : "outline"}>
                  {copied ? (<><Check className="mr-1 h-3 w-3" />Copied!</>) : (<><Copy className="mr-1 h-3 w-3" />Copy</>)}
                </Button>
              </div>
              <div className="rounded-md border border-blue-500/30 bg-blue-500/5 p-3 text-sm space-y-2">
                <p className="font-semibold">Cara pakai:</p>
                <ol className="list-decimal list-inside space-y-1 text-xs text-muted-foreground">
                  <li>Buka <a href="https://colab.research.google.com" target="_blank" rel="noopener noreferrer" className="text-blue-500 underline inline-flex items-center gap-0.5">Google Colab <ExternalLink className="h-3 w-3" /></a></li>
                  <li>Buat notebook baru (New Notebook)</li>
                  <li>Runtime → Change runtime type → T4 GPU</li>
                  <li>Paste command ke cell pertama</li>
                  <li>Klik Run (Shift+Enter)</li>
                  <li>Tunggu download + transcribe selesai</li>
                  <li>Subtitle otomatis ter-upload ke CineStream</li>
                </ol>
              </div>
              <div className="rounded-md border border-orange-500/30 bg-orange-500/5 p-3 text-xs text-orange-600">
                <p className="flex items-start gap-2">
                  <AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />
                  <span><strong>Penting:</strong> Model "Medium" butuh ~1.5GB RAM dan 15-30 menit. "Large v3" butuh ~3GB dan 30-60 menit. Pastikan pakai GPU runtime.</span>
                </p>
              </div>
              <div>
                <Label>Python Command (copy semua)</Label>
                <textarea readOnly value={command} className="mt-1 min-h-[400px] w-full rounded-md border border-input bg-zinc-950 px-3 py-2 font-mono text-xs text-green-400" onClick={(e) => (e.target as HTMLTextAreaElement).select()} />
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
