"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Loader2, Copy, Check, Sparkles, Film, ExternalLink, AlertCircle } from "lucide-react";
import { SubtitleSearch, type MediaResult } from "./subtitle-search";

const VPS_API_BASE =
  process.env.NEXT_PUBLIC_API_URL || "https://api.cinestream.biz.id";

export function SubtitleGenerate() {
  const [apiKey, setApiKey] = useState("");
  const [selectedMedia, setSelectedMedia] = useState<MediaResult | null>(null);
  const [season, setSeason] = useState("1");
  const [episode, setEpisode] = useState("1");
  const [command, setCommand] = useState("");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("admin_api_key");
    if (saved) setApiKey(saved);
  }, []);

  useEffect(() => {
    if (apiKey) localStorage.setItem("admin_api_key", apiKey);
  }, [apiKey]);

  // Reset season/episode kalau pilih movie
  useEffect(() => {
    if (selectedMedia?.type === "movie") {
      setSeason("");
      setEpisode("");
    } else if (selectedMedia?.type === "tv" && !season) {
      setSeason("1");
      setEpisode("1");
    }
  }, [selectedMedia]);

  const handleGenerate = () => {
    if (!selectedMedia || !apiKey) return;

    const isTV = selectedMedia.type === "tv";
    const title = selectedMedia.title;
    const cinemacityId = selectedMedia.cinemacity_id;
    const slug = selectedMedia.slug;
    const type = selectedMedia.type;

    // Build stream URL
    const streamParams = new URLSearchParams({
      slug: slug,
      type: type,
    });
    if (isTV && season) streamParams.set("season", season);
    if (isTV && episode) streamParams.set("episode", episode);
    const streamUrl = `${VPS_API_BASE}/api/stream/play/${cinemacityId}?${streamParams.toString()}`;

    // Generate Python script untuk Colab
    const colabScript = `# ============================================================
# CINESTREAM SUBTITLE GENERATOR
# Auto-generated by cinestream.biz.id/admin/subtitle/generate
# ============================================================
# Film: ${title}
# Type: ${type}
# Cinemacity ID: ${cinemacityId}
${isTV ? `# Season: ${season}, Episode: ${episode}` : "# Season/Episode: N/A (movie)"}
# Model: Whisper small (Indonesia)
# ============================================================

# === CONFIGURATION (auto-filled) ===
STREAM_URL = "${streamUrl}"
TITLE = "${title.replace(/"/g, '\"')}"
TYPE = "${type}"
SEASON = ${isTV && season ? `"${season}"` : "None"}
EPISODE = ${isTV && episode ? `"${episode}"` : "None"}
ADMIN_API_KEY = "${apiKey}"
WORKER_URL = "https://cinestream.biz.id"
WATERMARK = "nonton streaming film terupdate hanya di cinestream.biz.id"

# === STEP 1: Install Whisper ===
import subprocess
import sys
print("Installing openai-whisper...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "openai-whisper"])
print("✅ Whisper installed")

# === STEP 2: Download audio from stream ===
# ffmpeg sudah pre-installed di Google Colab
# FIX: Tambah User-Agent (Cloudflare block ffmpeg default UA "Lavf/...")
#      + reconnect flags + timeout supaya tidak hang
#      + progress output supaya user lihat progress
print("Downloading audio from stream...")
print(f"Stream URL: {STREAM_URL}")
print("This may take 5-15 minutes depending on film length...")
subprocess.run([
    "ffmpeg", "-y",
    "-user_agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "-headers", "Origin: https://cinestream.biz.id\\r\\n",
    "-reconnect", "1",
    "-reconnect_streamed", "1",
    "-reconnect_at_eof", "1",
    "-reconnect_delay_max", "10",
    "-rw_timeout", "60000000",   # 60s timeout per operation (microseconds)
    "-i", STREAM_URL,
    "-vn",                       # no video
    "-acodec", "pcm_s16le",      # WAV 16-bit
    "-ar", "16000",              # 16kHz (Whisper optimal)
    "-ac", "1",                  # mono
    "-progress", "pipe:1",       # progress to stdout
    "audio.wav"
], check=True)
print("Audio downloaded: audio.wav")

# === STEP 3: Run Whisper transcription ===
import whisper
print("\nLoading Whisper model (small)...")
print("⏳ First run akan download model (~500MB), tunggu sebentar...")
model = whisper.load_model("small")
print("✅ Model loaded")

print("\nTranscribing audio (language=id)...")
result = model.transcribe("audio.wav", language="id", task="transcribe", verbose=True)
print(f"✅ Transcribed {len(result['segments'])} segments")

# === STEP 4: Convert to VTT + add watermark ===
def seconds_to_vtt(sec):
    h = int(sec // 3600)
    m = int((sec % 3600) // 60)
    s = int(sec % 60)
    ms = int((sec % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"

vtt_lines = ["WEBVTT", "", "NOTE", f"Subtitle generated by CineStream - {WORKER_URL}", ""]

# Watermark di awal (0-1.5 detik)
vtt_lines.append("00:00:00.000 --> 00:00:01.500")
vtt_lines.append(WATERMARK)
vtt_lines.append("")

segments = result["segments"]
next_wm = 300  # watermark setiap 5 menit

for seg in segments:
    start = seg["start"]
    end = seg["end"]
    text = seg["text"].strip()

    # Insert watermark kalau sudah lewat 5 menit
    while start >= next_wm + 0.6:
        wm_start = next_wm
        wm_end = next_wm + 0.5
        if wm_end <= start:
            vtt_lines.append(f"{seconds_to_vtt(wm_start)} --> {seconds_to_vtt(wm_end)}")
            vtt_lines.append(WATERMARK)
            vtt_lines.append("")
        next_wm += 300

    vtt_lines.append(f"{seconds_to_vtt(start)} --> {seconds_to_vtt(end)}")
    vtt_lines.append(text)
    vtt_lines.append("")

vtt_content = "\n".join(vtt_lines)
print(f"\n✅ VTT generated ({len(vtt_content)} chars, {len(segments)} cues)")

# Save VTT to file (backup)
with open("subtitle.vtt", "w", encoding="utf-8") as f:
    f.write(vtt_content)
print("✅ Saved to subtitle.vtt (backup)")

# === STEP 5: Upload ke CineStream API ===
import requests
print("\nUploading subtitle to CineStream...")
resp = requests.post(
    f"{WORKER_URL}/api/admin/subtitle",
    headers={
        "Content-Type": "application/json",
        "X-Admin-API-Key": ADMIN_API_KEY,
    },
    json={
        "title": TITLE,
        "type": TYPE,
        "season": SEASON,
        "episode": EPISODE,
        "subtitle_text": vtt_content,
        "release_name": "whisper-small-auto-id",
        "offset_seconds": 0,
    },
    timeout=30,
)
print(f"\n{'='*50}")
print(f"Upload status: {resp.status_code}")
print(f"Response: {resp.json()}")
if resp.status_code == 200:
    print("\n🎉 SUCCESS! Subtitle sudah tersimpan di CineStream.")
    print(f"   Buka {WORKER_URL} → cari film '{TITLE}' → play → subtitle muncul otomatis.")
else:
    print("\n❌ FAILED. Cek error di atas.")
print(f"{'='*50}")
`;

    setCommand(colabScript);
    setCopied(false);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(command);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch {
      // Fallback untuk browser yang tidak support clipboard API
      const textarea = document.createElement("textarea");
      textarea.value = command;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  const isTV = selectedMedia?.type === "tv";

  return (
    <div className="space-y-6">
      {/* API Key */}
      {!apiKey && (
        <div className="rounded-lg border border-yellow-500/30 bg-yellow-500/5 p-4">
          <Label className="text-sm font-semibold">Admin API Key</Label>
          <Input
            type="password"
            placeholder="Paste your ADMIN_API_KEY"
            value={apiKey}
            onChange={(e) => setApiKey(e.target.value)}
            className="mt-1"
          />
        </div>
      )}

      {apiKey && (
        <>
          {/* Step 1: Cari Film */}
          <SubtitleSearch onSelect={setSelectedMedia} />

          {/* Step 2: Pilih Season/Episode (untuk TV) */}
          {selectedMedia && isTV && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <h2 className="text-lg font-semibold">2. Pilih Episode</h2>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label htmlFor="season">Season</Label>
                  <Input
                    id="season"
                    type="number"
                    value={season}
                    onChange={(e) => setSeason(e.target.value)}
                    placeholder="1"
                  />
                </div>
                <div>
                  <Label htmlFor="episode">Episode</Label>
                  <Input
                    id="episode"
                    type="number"
                    value={episode}
                    onChange={(e) => setEpisode(e.target.value)}
                    placeholder="1"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Step 3: Generate */}
          {selectedMedia && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <h2 className="flex items-center gap-2 text-lg font-semibold">
                <Sparkles className="h-5 w-5 text-primary" />
                {isTV ? "3. Generate Colab Command" : "2. Generate Colab Command"}
              </h2>

              {/* Info summary */}
              <div className="rounded-md bg-muted/50 p-3 text-sm">
                <div className="flex items-center gap-2">
                  <Film className="h-4 w-4 text-muted-foreground" />
                  <span className="font-medium">{selectedMedia.title}</span>
                </div>
                <div className="mt-2 flex flex-wrap gap-1">
                  <Badge variant="secondary" className="text-[10px]">
                    {selectedMedia.type === "tv" ? "TV Series" : "Movie"}
                  </Badge>
                  {isTV && season && (
                    <Badge variant="outline" className="text-[10px]">S{season}</Badge>
                  )}
                  {isTV && episode && (
                    <Badge variant="outline" className="text-[10px]">E{episode}</Badge>
                  )}
                  <Badge variant="outline" className="text-[10px]">ID: {selectedMedia.cinemacity_id}</Badge>
                </div>
              </div>

              <Button onClick={handleGenerate} className="w-full" size="lg">
                <Sparkles className="mr-2 h-4 w-4" />
                Generate Colab Command
              </Button>
            </div>
          )}

          {/* Step 4: Copy Command */}
          {command && (
            <div className="space-y-3 rounded-lg border bg-card p-4">
              <div className="flex items-center justify-between">
                <h2 className="flex items-center gap-2 text-lg font-semibold">
                  <Check className="h-5 w-5 text-green-500" />
                  {isTV ? "4. Copy & Paste ke Colab" : "3. Copy & Paste ke Colab"}
                </h2>
                <Button onClick={handleCopy} size="sm" variant={copied ? "default" : "outline"}>
                  {copied ? (
                    <>
                      <Check className="mr-1 h-3 w-3" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="mr-1 h-3 w-3" />
                      Copy
                    </>
                  )}
                </Button>
              </div>

              {/* Instructions */}
              <div className="rounded-md border border-blue-500/30 bg-blue-500/5 p-3 text-sm space-y-2">
                <p className="font-semibold">Cara pakai:</p>
                <ol className="list-decimal list-inside space-y-1 text-xs text-muted-foreground">
                  <li>
                    Buka{" "}
                    <a
                      href="https://colab.research.google.com"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-500 underline inline-flex items-center gap-0.5"
                    >
                      Google Colab <ExternalLink className="h-3 w-3" />
                    </a>
                  </li>
                  <li>Buat notebook baru (New Notebook)</li>
                  <li>Paste command di bawah ke cell pertama</li>
                  <li>Klik Run (atau Shift+Enter)</li>
                  <li>Tunggu ~10-15 menit (download audio + Whisper transcription)</li>
                  <li>Subtitle otomatis ter-upload ke CineStream</li>
                </ol>
              </div>

              {/* Warning */}
              <div className="rounded-md border border-orange-500/30 bg-orange-500/5 p-3 text-xs text-orange-600">
                <p className="flex items-start gap-2">
                  <AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />
                  <span>
                    <strong>Penting:</strong> Pastikan Colab pakai GPU runtime
                    (Runtime → Change runtime type → T4 GPU) untuk kecepatan optimal.
                    Tanpa GPU, Whisper small butuh 30-60 menit per film.
                  </span>
                </p>
              </div>

              {/* Command output */}
              <div>
                <Label>Python Command (copy semua)</Label>
                <textarea
                  readOnly
                  value={command}
                  className="mt-1 min-h-[400px] w-full rounded-md border border-input bg-zinc-950 px-3 py-2 font-mono text-xs text-green-400"
                  onClick={(e) => (e.target as HTMLTextAreaElement).select()}
                />
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
